/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.7-dev */

#ifndef PB_SRC_CORE_COM_SERIAL_INTERFACE_PB_H_INCLUDED
#define PB_SRC_CORE_COM_SERIAL_INTERFACE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _TestRequest {
    uint32_t testA;
    uint32_t testB;
} TestRequest;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define TestRequest_init_default                 {0, 0}
#define TestRequest_init_zero                    {0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define TestRequest_testA_tag                    1
#define TestRequest_testB_tag                    2

/* Struct field encoding specification for nanopb */
#define TestRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   testA,             1) \
X(a, STATIC,   SINGULAR, UINT32,   testB,             2)
#define TestRequest_CALLBACK NULL
#define TestRequest_DEFAULT NULL

extern const pb_msgdesc_t TestRequest_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define TestRequest_fields &TestRequest_msg

/* Maximum encoded size of messages (where known) */
#define TestRequest_size                         12

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
