/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.7-dev */

#include "src/core/com/serial/serial_interface.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(Header, Header, AUTO)


PB_BIND(BaseMessage, BaseMessage, AUTO)


PB_BIND(AckNackMessage, AckNackMessage, AUTO)


PB_BIND(PingMessage, PingMessage, AUTO)


PB_BIND(SystemTick, SystemTick, AUTO)


PB_BIND(ConsoleMessage, ConsoleMessage, AUTO)


PB_BIND(SystemInfoMessage, SystemInfoMessage, AUTO)


PB_BIND(ParamData, ParamData, AUTO)


PB_BIND(ParamIOMessage, ParamIOMessage, AUTO)







#ifndef PB_CONVERT_DOUBLE_FLOAT
/* On some platforms (such as AVR), double is really float.
 * To be able to encode/decode double on these platforms, you need.
 * to define PB_CONVERT_DOUBLE_FLOAT in pb.h or compiler command line.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)
#endif

