/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.7 */

#include "src/core/com/serial/serial_interface.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(Header, Header, AUTO)


PB_BIND(BaseMessage, BaseMessage, AUTO)


PB_BIND(AckNackMessage, AckNackMessage, AUTO)


PB_BIND(PingMessage, PingMessage, AUTO)


PB_BIND(SystemTick, SystemTick, AUTO)


PB_BIND(ConsoleMessage, ConsoleMessage, AUTO)


PB_BIND(SystemInfoMessage, SystemInfoMessage, AUTO)


PB_BIND(ParamIOMessage, ParamIOMessage, AUTO)


PB_BIND(SystemControlMessage, SystemControlMessage, AUTO)


PB_BIND(SystemControlMessage_ManualICtrlSetPoint, SystemControlMessage_ManualICtrlSetPoint, AUTO)


PB_BIND(SwitchModeMessage, SwitchModeMessage, AUTO)


PB_BIND(SystemDataMessage, SystemDataMessage, AUTO)


PB_BIND(SystemDataMessage_ADCPhaseCurrents, SystemDataMessage_ADCPhaseCurrents, AUTO)


PB_BIND(SystemDataMessage_ADCSystemMeasurements, SystemDataMessage_ADCSystemMeasurements, AUTO)


PB_BIND(SystemDataMessage_ADCPhaseVoltages, SystemDataMessage_ADCPhaseVoltages, AUTO)


PB_BIND(SystemDataMessage_StateEstimates, SystemDataMessage_StateEstimates, AUTO)











