/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.7-dev */

#include "src/core/com/serial/serial_interface.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(Header, Header, AUTO)


PB_BIND(BaseMessage, BaseMessage, AUTO)


PB_BIND(AckNackMessage, AckNackMessage, AUTO)


PB_BIND(PingMessage, PingMessage, AUTO)


PB_BIND(SystemTick, SystemTick, AUTO)


PB_BIND(ConsoleMessage, ConsoleMessage, AUTO)


PB_BIND(SystemInfoMessage, SystemInfoMessage, AUTO)


PB_BIND(ParamIOMessage, ParamIOMessage, AUTO)


PB_BIND(SystemControlMessage, SystemControlMessage, AUTO)








