"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import serial_interface_pb2
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _SimulatorSubId:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _SimulatorSubIdEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_SimulatorSubId.ValueType], builtins.type):  # noqa: F821
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    SIM_FLOAT_ECHO: _SimulatorSubId.ValueType  # 1
    """Echo a floating point value for Matlab integration"""

class SimulatorSubId(_SimulatorSubId, metaclass=_SimulatorSubIdEnumTypeWrapper):
    """Sub-IDs for simulator-specific messages sent over the serial link."""

SIM_FLOAT_ECHO: SimulatorSubId.ValueType  # 1
"""Echo a floating point value for Matlab integration"""
global___SimulatorSubId = SimulatorSubId

class SimulatorFloatEcho(google.protobuf.message.Message):
    """Echo message used to verify the Matlab serial interface with the simulator."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    HEADER_FIELD_NUMBER: builtins.int
    VALUE_FIELD_NUMBER: builtins.int
    @property
    def header(self) -> serial_interface_pb2.Header: ...
    value: builtins.float
    def __init__(
        self,
        *,
        header: serial_interface_pb2.Header | None = ...,
        value: builtins.float | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["header", b"header", "value", b"value"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["header", b"header", "value", b"value"]) -> None: ...

global___SimulatorFloatEcho = SimulatorFloatEcho
