"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import serial_interface_pb2
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

class _SystemControlSubId:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType
class _SystemControlSubIdEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_SystemControlSubId.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
    RESET: SystemControlSubId.ValueType = ...  # 1
    """Reset the system"""

    MOTOR: SystemControlSubId.ValueType = ...  # 2
    """Inject manual motor control commands"""

    CAL_ADC: SystemControlSubId.ValueType = ...  # 3
    """Calibrate the ADC"""

    MANUAL_INNER_LOOP: SystemControlSubId.ValueType = ...  # 4
    """Manual inner loop control enable/disable"""

    MANUAL_INNER_LOOP_REF: SystemControlSubId.ValueType = ...  # 5
    """New references to use for manual inner loop control"""

    ENABLE_STREAM_PHASE_CURRENTS: SystemControlSubId.ValueType = ...  # 6
    """Enable streaming of phase currents"""

    DISABLE_STREAM_PHASE_CURRENTS: SystemControlSubId.ValueType = ...  # 7
    """Disable streaming of phase currents"""

    ENABLE_STREAM_SYSTEM_VOLTAGES: SystemControlSubId.ValueType = ...  # 8
    """Enable streaming of system voltages"""

    DISABLE_STREAM_SYSTEM_VOLTAGES: SystemControlSubId.ValueType = ...  # 9
    """Disable streaming of system voltages"""

    ENABLE_STREAM_PHASE_VOLTAGES: SystemControlSubId.ValueType = ...  # 10
    """Enable streaming of phase voltage commands"""

    DISABLE_STREAM_PHASE_VOLTAGES: SystemControlSubId.ValueType = ...  # 11
    """Disable streaming of phase voltage commands"""

    ENABLE_STREAM_STATE_ESTIMATES: SystemControlSubId.ValueType = ...  # 12
    """Enable streaming of state estimates"""

    DISABLE_STREAM_STATE_ESTIMATES: SystemControlSubId.ValueType = ...  # 13
    """Disable streaming of state estimates"""

    ARM: SystemControlSubId.ValueType = ...  # 14
    """Arm the motor control system"""

    DISARM: SystemControlSubId.ValueType = ...  # 15
    """Disarm the motor control system"""

    ENGAGE: SystemControlSubId.ValueType = ...  # 16
    """Engage the motor control system"""

    DISENGAGE: SystemControlSubId.ValueType = ...  # 17
    """Disengage the motor control system"""

    FAULT: SystemControlSubId.ValueType = ...  # 18
    """Panic the motor control system"""

    EMERGENCY_STOP: SystemControlSubId.ValueType = ...  # 19
    """Emergency stop the motor control system"""

class SystemControlSubId(_SystemControlSubId, metaclass=_SystemControlSubIdEnumTypeWrapper):
    pass

RESET: SystemControlSubId.ValueType = ...  # 1
"""Reset the system"""

MOTOR: SystemControlSubId.ValueType = ...  # 2
"""Inject manual motor control commands"""

CAL_ADC: SystemControlSubId.ValueType = ...  # 3
"""Calibrate the ADC"""

MANUAL_INNER_LOOP: SystemControlSubId.ValueType = ...  # 4
"""Manual inner loop control enable/disable"""

MANUAL_INNER_LOOP_REF: SystemControlSubId.ValueType = ...  # 5
"""New references to use for manual inner loop control"""

ENABLE_STREAM_PHASE_CURRENTS: SystemControlSubId.ValueType = ...  # 6
"""Enable streaming of phase currents"""

DISABLE_STREAM_PHASE_CURRENTS: SystemControlSubId.ValueType = ...  # 7
"""Disable streaming of phase currents"""

ENABLE_STREAM_SYSTEM_VOLTAGES: SystemControlSubId.ValueType = ...  # 8
"""Enable streaming of system voltages"""

DISABLE_STREAM_SYSTEM_VOLTAGES: SystemControlSubId.ValueType = ...  # 9
"""Disable streaming of system voltages"""

ENABLE_STREAM_PHASE_VOLTAGES: SystemControlSubId.ValueType = ...  # 10
"""Enable streaming of phase voltage commands"""

DISABLE_STREAM_PHASE_VOLTAGES: SystemControlSubId.ValueType = ...  # 11
"""Disable streaming of phase voltage commands"""

ENABLE_STREAM_STATE_ESTIMATES: SystemControlSubId.ValueType = ...  # 12
"""Enable streaming of state estimates"""

DISABLE_STREAM_STATE_ESTIMATES: SystemControlSubId.ValueType = ...  # 13
"""Disable streaming of state estimates"""

ARM: SystemControlSubId.ValueType = ...  # 14
"""Arm the motor control system"""

DISARM: SystemControlSubId.ValueType = ...  # 15
"""Disarm the motor control system"""

ENGAGE: SystemControlSubId.ValueType = ...  # 16
"""Engage the motor control system"""

DISENGAGE: SystemControlSubId.ValueType = ...  # 17
"""Disengage the motor control system"""

FAULT: SystemControlSubId.ValueType = ...  # 18
"""Panic the motor control system"""

EMERGENCY_STOP: SystemControlSubId.ValueType = ...  # 19
"""Emergency stop the motor control system"""

global___SystemControlSubId = SystemControlSubId


class SystemControlMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    HEADER_FIELD_NUMBER: builtins.int
    DATA_FIELD_NUMBER: builtins.int
    @property
    def header(self) -> serial_interface_pb2.Header: ...
    data: builtins.bytes = ...
    def __init__(self,
        *,
        header : typing.Optional[serial_interface_pb2.Header] = ...,
        data : typing.Optional[builtins.bytes] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["data",b"data","header",b"header"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["data",b"data","header",b"header"]) -> None: ...
global___SystemControlMessage = SystemControlMessage
