# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: system_control.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import nanopb_pb2 as nanopb__pb2
import serial_interface_pb2 as serial__interface__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='system_control.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14system_control.proto\x1a\x0cnanopb.proto\x1a\x16serial_interface.proto\"D\n\x14SystemControlMessage\x12\x17\n\x06header\x18\x01 \x02(\x0b\x32\x07.Header\x12\x13\n\x04\x64\x61ta\x18\x02 \x01(\x0c\x42\x05\x92?\x02\x08@*\xae\x03\n\x12SystemControlSubId\x12\t\n\x05RESET\x10\x01\x12\t\n\x05MOTOR\x10\x02\x12\x0b\n\x07\x43\x41L_ADC\x10\x03\x12\x15\n\x11MANUAL_INNER_LOOP\x10\x04\x12\x19\n\x15MANUAL_INNER_LOOP_REF\x10\x05\x12 \n\x1c\x45NABLE_STREAM_PHASE_CURRENTS\x10\x06\x12!\n\x1d\x44ISABLE_STREAM_PHASE_CURRENTS\x10\x07\x12!\n\x1d\x45NABLE_STREAM_SYSTEM_VOLTAGES\x10\x08\x12\"\n\x1e\x44ISABLE_STREAM_SYSTEM_VOLTAGES\x10\t\x12 \n\x1c\x45NABLE_STREAM_PHASE_VOLTAGES\x10\n\x12!\n\x1d\x44ISABLE_STREAM_PHASE_VOLTAGES\x10\x0b\x12!\n\x1d\x45NABLE_STREAM_STATE_ESTIMATES\x10\x0c\x12\"\n\x1e\x44ISABLE_STREAM_STATE_ESTIMATES\x10\r\x12\x07\n\x03\x41RM\x10\x0e\x12\n\n\x06\x45NGAGE\x10\x0f\x12\x0b\n\x07\x44ISABLE\x10\x10\x12\t\n\x05\x46\x41ULT\x10\x11'
  ,
  dependencies=[nanopb__pb2.DESCRIPTOR,serial__interface__pb2.DESCRIPTOR,])

_SYSTEMCONTROLSUBID = _descriptor.EnumDescriptor(
  name='SystemControlSubId',
  full_name='SystemControlSubId',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='RESET', index=0, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MOTOR', index=1, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CAL_ADC', index=2, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MANUAL_INNER_LOOP', index=3, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MANUAL_INNER_LOOP_REF', index=4, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ENABLE_STREAM_PHASE_CURRENTS', index=5, number=6,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DISABLE_STREAM_PHASE_CURRENTS', index=6, number=7,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ENABLE_STREAM_SYSTEM_VOLTAGES', index=7, number=8,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DISABLE_STREAM_SYSTEM_VOLTAGES', index=8, number=9,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ENABLE_STREAM_PHASE_VOLTAGES', index=9, number=10,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DISABLE_STREAM_PHASE_VOLTAGES', index=10, number=11,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ENABLE_STREAM_STATE_ESTIMATES', index=11, number=12,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DISABLE_STREAM_STATE_ESTIMATES', index=12, number=13,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ARM', index=13, number=14,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ENGAGE', index=14, number=15,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DISABLE', index=15, number=16,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='FAULT', index=16, number=17,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=133,
  serialized_end=563,
)
_sym_db.RegisterEnumDescriptor(_SYSTEMCONTROLSUBID)

SystemControlSubId = enum_type_wrapper.EnumTypeWrapper(_SYSTEMCONTROLSUBID)
RESET = 1
MOTOR = 2
CAL_ADC = 3
MANUAL_INNER_LOOP = 4
MANUAL_INNER_LOOP_REF = 5
ENABLE_STREAM_PHASE_CURRENTS = 6
DISABLE_STREAM_PHASE_CURRENTS = 7
ENABLE_STREAM_SYSTEM_VOLTAGES = 8
DISABLE_STREAM_SYSTEM_VOLTAGES = 9
ENABLE_STREAM_PHASE_VOLTAGES = 10
DISABLE_STREAM_PHASE_VOLTAGES = 11
ENABLE_STREAM_STATE_ESTIMATES = 12
DISABLE_STREAM_STATE_ESTIMATES = 13
ARM = 14
ENGAGE = 15
DISABLE = 16
FAULT = 17



_SYSTEMCONTROLMESSAGE = _descriptor.Descriptor(
  name='SystemControlMessage',
  full_name='SystemControlMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='SystemControlMessage.header', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='SystemControlMessage.data', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\222?\002\010@', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=130,
)

_SYSTEMCONTROLMESSAGE.fields_by_name['header'].message_type = serial__interface__pb2._HEADER
DESCRIPTOR.message_types_by_name['SystemControlMessage'] = _SYSTEMCONTROLMESSAGE
DESCRIPTOR.enum_types_by_name['SystemControlSubId'] = _SYSTEMCONTROLSUBID
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SystemControlMessage = _reflection.GeneratedProtocolMessageType('SystemControlMessage', (_message.Message,), {
  'DESCRIPTOR' : _SYSTEMCONTROLMESSAGE,
  '__module__' : 'system_control_pb2'
  # @@protoc_insertion_point(class_scope:SystemControlMessage)
  })
_sym_db.RegisterMessage(SystemControlMessage)


_SYSTEMCONTROLMESSAGE.fields_by_name['data']._options = None
# @@protoc_insertion_point(module_scope)
