# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: system_control.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import nanopb_pb2 as nanopb__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='system_control.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14system_control.proto\x1a\x0cnanopb.proto*\xcb\x05\n\x12SystemControlSubId\x12\x1a\n\x16SUB_MSG_SYS_CTRL_RESET\x10\x01\x12\x1a\n\x16SUB_MSG_SYS_CTRL_MOTOR\x10\x02\x12\x1c\n\x18SUB_MSG_SYS_CTRL_CAL_ADC\x10\x03\x12&\n\"SUB_MSG_SYS_CTRL_MANUAL_INNER_LOOP\x10\x04\x12*\n&SUB_MSG_SYS_CTRL_MANUAL_INNER_LOOP_REF\x10\x05\x12(\n$SUB_MSG_ENABLE_STREAM_PHASE_CURRENTS\x10\x06\x12)\n%SUB_MSG_DISABLE_STREAM_PHASE_CURRENTS\x10\x07\x12)\n%SUB_MSG_ENABLE_STREAM_SYSTEM_VOLTAGES\x10\x08\x12*\n&SUB_MSG_DISABLE_STREAM_SYSTEM_VOLTAGES\x10\t\x12(\n$SUB_MSG_ENABLE_STREAM_PHASE_VOLTAGES\x10\n\x12)\n%SUB_MSG_DISABLE_STREAM_PHASE_VOLTAGES\x10\x0b\x12)\n%SUB_MSG_ENABLE_STREAM_STATE_ESTIMATES\x10\x0c\x12*\n&SUB_MSG_DISABLE_STREAM_STATE_ESTIMATES\x10\r\x12\x18\n\x14SUB_MSG_SYS_CTRL_ARM\x10\x0e\x12\x1b\n\x17SUB_MSG_SYS_CTRL_DISARM\x10\x0f\x12\x1b\n\x17SUB_MSG_SYS_CTRL_ENGAGE\x10\x10\x12\x1e\n\x1aSUB_MSG_SYS_CTRL_DISENGAGE\x10\x11\x12\x1a\n\x16SUB_MSG_SYS_CTRL_FAULT\x10\x12\x12#\n\x1fSUB_MSG_SYS_CTRL_EMERGENCY_STOP\x10\x13'
  ,
  dependencies=[nanopb__pb2.DESCRIPTOR,])

_SYSTEMCONTROLSUBID = _descriptor.EnumDescriptor(
  name='SystemControlSubId',
  full_name='SystemControlSubId',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SUB_MSG_SYS_CTRL_RESET', index=0, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SUB_MSG_SYS_CTRL_MOTOR', index=1, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SUB_MSG_SYS_CTRL_CAL_ADC', index=2, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SUB_MSG_SYS_CTRL_MANUAL_INNER_LOOP', index=3, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SUB_MSG_SYS_CTRL_MANUAL_INNER_LOOP_REF', index=4, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SUB_MSG_ENABLE_STREAM_PHASE_CURRENTS', index=5, number=6,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SUB_MSG_DISABLE_STREAM_PHASE_CURRENTS', index=6, number=7,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SUB_MSG_ENABLE_STREAM_SYSTEM_VOLTAGES', index=7, number=8,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SUB_MSG_DISABLE_STREAM_SYSTEM_VOLTAGES', index=8, number=9,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SUB_MSG_ENABLE_STREAM_PHASE_VOLTAGES', index=9, number=10,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SUB_MSG_DISABLE_STREAM_PHASE_VOLTAGES', index=10, number=11,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SUB_MSG_ENABLE_STREAM_STATE_ESTIMATES', index=11, number=12,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SUB_MSG_DISABLE_STREAM_STATE_ESTIMATES', index=12, number=13,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SUB_MSG_SYS_CTRL_ARM', index=13, number=14,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SUB_MSG_SYS_CTRL_DISARM', index=14, number=15,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SUB_MSG_SYS_CTRL_ENGAGE', index=15, number=16,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SUB_MSG_SYS_CTRL_DISENGAGE', index=16, number=17,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SUB_MSG_SYS_CTRL_FAULT', index=17, number=18,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SUB_MSG_SYS_CTRL_EMERGENCY_STOP', index=18, number=19,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=39,
  serialized_end=754,
)
_sym_db.RegisterEnumDescriptor(_SYSTEMCONTROLSUBID)

SystemControlSubId = enum_type_wrapper.EnumTypeWrapper(_SYSTEMCONTROLSUBID)
SUB_MSG_SYS_CTRL_RESET = 1
SUB_MSG_SYS_CTRL_MOTOR = 2
SUB_MSG_SYS_CTRL_CAL_ADC = 3
SUB_MSG_SYS_CTRL_MANUAL_INNER_LOOP = 4
SUB_MSG_SYS_CTRL_MANUAL_INNER_LOOP_REF = 5
SUB_MSG_ENABLE_STREAM_PHASE_CURRENTS = 6
SUB_MSG_DISABLE_STREAM_PHASE_CURRENTS = 7
SUB_MSG_ENABLE_STREAM_SYSTEM_VOLTAGES = 8
SUB_MSG_DISABLE_STREAM_SYSTEM_VOLTAGES = 9
SUB_MSG_ENABLE_STREAM_PHASE_VOLTAGES = 10
SUB_MSG_DISABLE_STREAM_PHASE_VOLTAGES = 11
SUB_MSG_ENABLE_STREAM_STATE_ESTIMATES = 12
SUB_MSG_DISABLE_STREAM_STATE_ESTIMATES = 13
SUB_MSG_SYS_CTRL_ARM = 14
SUB_MSG_SYS_CTRL_DISARM = 15
SUB_MSG_SYS_CTRL_ENGAGE = 16
SUB_MSG_SYS_CTRL_DISENGAGE = 17
SUB_MSG_SYS_CTRL_FAULT = 18
SUB_MSG_SYS_CTRL_EMERGENCY_STOP = 19


DESCRIPTOR.enum_types_by_name['SystemControlSubId'] = _SYSTEMCONTROLSUBID
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


# @@protoc_insertion_point(module_scope)
