# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: system_data.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import nanopb_pb2 as nanopb__pb2
import serial_interface_pb2 as serial__interface__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='system_data.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11system_data.proto\x1a\x0cnanopb.proto\x1a\x16serial_interface.proto\":\n\x11SystemTickMessage\x12\x17\n\x06header\x18\x01 \x02(\x0b\x32\x07.Header\x12\x0c\n\x04tick\x18\x02 \x02(\r\"w\n\x0e\x43onsoleMessage\x12\x17\n\x06header\x18\x01 \x02(\x0b\x32\x07.Header\x12\x19\n\nthis_frame\x18\x02 \x02(\rB\x05\x92?\x02\x38\x08\x12\x1b\n\x0ctotal_frames\x18\x03 \x02(\rB\x05\x92?\x02\x38\x08\x12\x14\n\x04\x64\x61ta\x18\x04 \x02(\x0c\x42\x06\x92?\x03\x08\x80\x01\"\xa2\x01\n\x11SystemInfoMessage\x12\x17\n\x06header\x18\x01 \x02(\x0b\x32\x07.Header\x12\x12\n\nsystemTick\x18\x02 \x02(\r\x12\x1d\n\tswVersion\x18\x03 \x02(\tB\n\x92?\x02\x08\x10\x92?\x02x\x01\x12\x1f\n\x0b\x64\x65scription\x18\x04 \x02(\tB\n\x92?\x02\x08\x10\x92?\x02x\x01\x12 \n\x0cserialNumber\x18\x05 \x02(\tB\n\x92?\x02\x08\x10\x92?\x02x\x01\"y\n\x11SystemDataMessage\x12\x17\n\x06header\x18\x01 \x02(\x0b\x32\x07.Header\x12 \n\x02id\x18\x02 \x02(\x0e\x32\r.SystemDataIdB\x05\x92?\x02\x38\x08\x12\x11\n\ttimestamp\x18\x03 \x02(\r\x12\x16\n\x07payload\x18\x04 \x01(\x0c\x42\x05\x92?\x02\x08 \"=\n\x17\x41\x44\x43PhaseCurrentsPayload\x12\n\n\x02ia\x18\x01 \x02(\x02\x12\n\n\x02ib\x18\x02 \x02(\x02\x12\n\n\x02ic\x18\x03 \x02(\x02\"=\n\x17\x41\x44\x43PhaseVoltagesPayload\x12\n\n\x02va\x18\x01 \x02(\x02\x12\n\n\x02vb\x18\x02 \x02(\x02\x12\n\n\x02vc\x18\x03 \x02(\x02\"^\n\x18\x41\x44\x43SystemVoltagesPayload\x12\r\n\x05v_mcu\x18\x01 \x02(\x02\x12\x11\n\tv_dc_link\x18\x02 \x02(\x02\x12\x0e\n\x06v_temp\x18\x03 \x02(\x02\x12\x10\n\x08v_isense\x18\x04 \x02(\x02\"=\n\x15StateEstimatesPayload\x12\x11\n\ttheta_est\x18\x01 \x02(\x02\x12\x11\n\tomega_est\x18\x02 \x02(\x02*\x82\x01\n\x0cSystemDataId\x12\x14\n\x10SYS_DATA_INVALID\x10\x00\x12\x16\n\x12\x41\x44\x43_PHASE_CURRENTS\x10\x01\x12\x16\n\x12\x41\x44\x43_PHASE_VOLTAGES\x10\x02\x12\x13\n\x0fSTATE_ESTIMATES\x10\x03\x12\x17\n\x13\x41\x44\x43_SYSTEM_VOLTAGES\x10\x04'
  ,
  dependencies=[nanopb__pb2.DESCRIPTOR,serial__interface__pb2.DESCRIPTOR,])

_SYSTEMDATAID = _descriptor.EnumDescriptor(
  name='SystemDataId',
  full_name='SystemDataId',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SYS_DATA_INVALID', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ADC_PHASE_CURRENTS', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ADC_PHASE_VOLTAGES', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='STATE_ESTIMATES', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ADC_SYSTEM_VOLTAGES', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=814,
  serialized_end=944,
)
_sym_db.RegisterEnumDescriptor(_SYSTEMDATAID)

SystemDataId = enum_type_wrapper.EnumTypeWrapper(_SYSTEMDATAID)
SYS_DATA_INVALID = 0
ADC_PHASE_CURRENTS = 1
ADC_PHASE_VOLTAGES = 2
STATE_ESTIMATES = 3
ADC_SYSTEM_VOLTAGES = 4



_SYSTEMTICKMESSAGE = _descriptor.Descriptor(
  name='SystemTickMessage',
  full_name='SystemTickMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='SystemTickMessage.header', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tick', full_name='SystemTickMessage.tick', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=59,
  serialized_end=117,
)


_CONSOLEMESSAGE = _descriptor.Descriptor(
  name='ConsoleMessage',
  full_name='ConsoleMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='ConsoleMessage.header', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='this_frame', full_name='ConsoleMessage.this_frame', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\222?\0028\010', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='total_frames', full_name='ConsoleMessage.total_frames', index=2,
      number=3, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\222?\0028\010', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='ConsoleMessage.data', index=3,
      number=4, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\222?\003\010\200\001', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=119,
  serialized_end=238,
)


_SYSTEMINFOMESSAGE = _descriptor.Descriptor(
  name='SystemInfoMessage',
  full_name='SystemInfoMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='SystemInfoMessage.header', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='systemTick', full_name='SystemInfoMessage.systemTick', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='swVersion', full_name='SystemInfoMessage.swVersion', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\222?\002\010\020\222?\002x\001', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='description', full_name='SystemInfoMessage.description', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\222?\002\010\020\222?\002x\001', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='serialNumber', full_name='SystemInfoMessage.serialNumber', index=4,
      number=5, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\222?\002\010\020\222?\002x\001', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=241,
  serialized_end=403,
)


_SYSTEMDATAMESSAGE = _descriptor.Descriptor(
  name='SystemDataMessage',
  full_name='SystemDataMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='SystemDataMessage.header', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='id', full_name='SystemDataMessage.id', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\222?\0028\010', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='SystemDataMessage.timestamp', index=2,
      number=3, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='payload', full_name='SystemDataMessage.payload', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\222?\002\010 ', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=405,
  serialized_end=526,
)


_ADCPHASECURRENTSPAYLOAD = _descriptor.Descriptor(
  name='ADCPhaseCurrentsPayload',
  full_name='ADCPhaseCurrentsPayload',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ia', full_name='ADCPhaseCurrentsPayload.ia', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ib', full_name='ADCPhaseCurrentsPayload.ib', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ic', full_name='ADCPhaseCurrentsPayload.ic', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=528,
  serialized_end=589,
)


_ADCPHASEVOLTAGESPAYLOAD = _descriptor.Descriptor(
  name='ADCPhaseVoltagesPayload',
  full_name='ADCPhaseVoltagesPayload',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='va', full_name='ADCPhaseVoltagesPayload.va', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='vb', full_name='ADCPhaseVoltagesPayload.vb', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='vc', full_name='ADCPhaseVoltagesPayload.vc', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=591,
  serialized_end=652,
)


_ADCSYSTEMVOLTAGESPAYLOAD = _descriptor.Descriptor(
  name='ADCSystemVoltagesPayload',
  full_name='ADCSystemVoltagesPayload',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='v_mcu', full_name='ADCSystemVoltagesPayload.v_mcu', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='v_dc_link', full_name='ADCSystemVoltagesPayload.v_dc_link', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='v_temp', full_name='ADCSystemVoltagesPayload.v_temp', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='v_isense', full_name='ADCSystemVoltagesPayload.v_isense', index=3,
      number=4, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=654,
  serialized_end=748,
)


_STATEESTIMATESPAYLOAD = _descriptor.Descriptor(
  name='StateEstimatesPayload',
  full_name='StateEstimatesPayload',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='theta_est', full_name='StateEstimatesPayload.theta_est', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='omega_est', full_name='StateEstimatesPayload.omega_est', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=750,
  serialized_end=811,
)

_SYSTEMTICKMESSAGE.fields_by_name['header'].message_type = serial__interface__pb2._HEADER
_CONSOLEMESSAGE.fields_by_name['header'].message_type = serial__interface__pb2._HEADER
_SYSTEMINFOMESSAGE.fields_by_name['header'].message_type = serial__interface__pb2._HEADER
_SYSTEMDATAMESSAGE.fields_by_name['header'].message_type = serial__interface__pb2._HEADER
_SYSTEMDATAMESSAGE.fields_by_name['id'].enum_type = _SYSTEMDATAID
DESCRIPTOR.message_types_by_name['SystemTickMessage'] = _SYSTEMTICKMESSAGE
DESCRIPTOR.message_types_by_name['ConsoleMessage'] = _CONSOLEMESSAGE
DESCRIPTOR.message_types_by_name['SystemInfoMessage'] = _SYSTEMINFOMESSAGE
DESCRIPTOR.message_types_by_name['SystemDataMessage'] = _SYSTEMDATAMESSAGE
DESCRIPTOR.message_types_by_name['ADCPhaseCurrentsPayload'] = _ADCPHASECURRENTSPAYLOAD
DESCRIPTOR.message_types_by_name['ADCPhaseVoltagesPayload'] = _ADCPHASEVOLTAGESPAYLOAD
DESCRIPTOR.message_types_by_name['ADCSystemVoltagesPayload'] = _ADCSYSTEMVOLTAGESPAYLOAD
DESCRIPTOR.message_types_by_name['StateEstimatesPayload'] = _STATEESTIMATESPAYLOAD
DESCRIPTOR.enum_types_by_name['SystemDataId'] = _SYSTEMDATAID
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SystemTickMessage = _reflection.GeneratedProtocolMessageType('SystemTickMessage', (_message.Message,), {
  'DESCRIPTOR' : _SYSTEMTICKMESSAGE,
  '__module__' : 'system_data_pb2'
  # @@protoc_insertion_point(class_scope:SystemTickMessage)
  })
_sym_db.RegisterMessage(SystemTickMessage)

ConsoleMessage = _reflection.GeneratedProtocolMessageType('ConsoleMessage', (_message.Message,), {
  'DESCRIPTOR' : _CONSOLEMESSAGE,
  '__module__' : 'system_data_pb2'
  # @@protoc_insertion_point(class_scope:ConsoleMessage)
  })
_sym_db.RegisterMessage(ConsoleMessage)

SystemInfoMessage = _reflection.GeneratedProtocolMessageType('SystemInfoMessage', (_message.Message,), {
  'DESCRIPTOR' : _SYSTEMINFOMESSAGE,
  '__module__' : 'system_data_pb2'
  # @@protoc_insertion_point(class_scope:SystemInfoMessage)
  })
_sym_db.RegisterMessage(SystemInfoMessage)

SystemDataMessage = _reflection.GeneratedProtocolMessageType('SystemDataMessage', (_message.Message,), {
  'DESCRIPTOR' : _SYSTEMDATAMESSAGE,
  '__module__' : 'system_data_pb2'
  # @@protoc_insertion_point(class_scope:SystemDataMessage)
  })
_sym_db.RegisterMessage(SystemDataMessage)

ADCPhaseCurrentsPayload = _reflection.GeneratedProtocolMessageType('ADCPhaseCurrentsPayload', (_message.Message,), {
  'DESCRIPTOR' : _ADCPHASECURRENTSPAYLOAD,
  '__module__' : 'system_data_pb2'
  # @@protoc_insertion_point(class_scope:ADCPhaseCurrentsPayload)
  })
_sym_db.RegisterMessage(ADCPhaseCurrentsPayload)

ADCPhaseVoltagesPayload = _reflection.GeneratedProtocolMessageType('ADCPhaseVoltagesPayload', (_message.Message,), {
  'DESCRIPTOR' : _ADCPHASEVOLTAGESPAYLOAD,
  '__module__' : 'system_data_pb2'
  # @@protoc_insertion_point(class_scope:ADCPhaseVoltagesPayload)
  })
_sym_db.RegisterMessage(ADCPhaseVoltagesPayload)

ADCSystemVoltagesPayload = _reflection.GeneratedProtocolMessageType('ADCSystemVoltagesPayload', (_message.Message,), {
  'DESCRIPTOR' : _ADCSYSTEMVOLTAGESPAYLOAD,
  '__module__' : 'system_data_pb2'
  # @@protoc_insertion_point(class_scope:ADCSystemVoltagesPayload)
  })
_sym_db.RegisterMessage(ADCSystemVoltagesPayload)

StateEstimatesPayload = _reflection.GeneratedProtocolMessageType('StateEstimatesPayload', (_message.Message,), {
  'DESCRIPTOR' : _STATEESTIMATESPAYLOAD,
  '__module__' : 'system_data_pb2'
  # @@protoc_insertion_point(class_scope:StateEstimatesPayload)
  })
_sym_db.RegisterMessage(StateEstimatesPayload)


_CONSOLEMESSAGE.fields_by_name['this_frame']._options = None
_CONSOLEMESSAGE.fields_by_name['total_frames']._options = None
_CONSOLEMESSAGE.fields_by_name['data']._options = None
_SYSTEMINFOMESSAGE.fields_by_name['swVersion']._options = None
_SYSTEMINFOMESSAGE.fields_by_name['description']._options = None
_SYSTEMINFOMESSAGE.fields_by_name['serialNumber']._options = None
_SYSTEMDATAMESSAGE.fields_by_name['id']._options = None
_SYSTEMDATAMESSAGE.fields_by_name['payload']._options = None
# @@protoc_insertion_point(module_scope)
