/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8 */

#include "serial_interface.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(Header, Header, AUTO)


PB_BIND(BaseMessage, BaseMessage, AUTO)


PB_BIND(AckNackMessage, AckNackMessage, AUTO)


PB_BIND(PingMessage, PingMessage, AUTO)






