/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.7 */

#include "system_data.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(SystemDataMessage, SystemDataMessage, AUTO)


PB_BIND(SystemDataMessage_ADCPhaseCurrents, SystemDataMessage_ADCPhaseCurrents, AUTO)


PB_BIND(SystemDataMessage_ADCPhaseVoltages, SystemDataMessage_ADCPhaseVoltages, AUTO)


PB_BIND(SystemDataMessage_ADCSystemVoltages, SystemDataMessage_ADCSystemVoltages, AUTO)


PB_BIND(SystemDataMessage_StateEstimates, SystemDataMessage_StateEstimates, AUTO)



