/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.8 */

#ifndef PB_SYSTEM_DATA_PB_H_INCLUDED
#define PB_SYSTEM_DATA_PB_H_INCLUDED
#include <pb.h>
#include "serial_interface.pb.h"
#include "motor_control.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _SystemDataId {
    SystemDataId_SYS_DATA_INVALID = 0, /* Invalid data ID */
    /* Composite Data Streams */
    SystemDataId_ADC_PHASE_CURRENTS = 1, /* ADC readings of the phase currents */
    SystemDataId_ADC_PHASE_VOLTAGES = 2, /* Voltage commands being sent to the motor */
    SystemDataId_ADC_SYSTEM_VOLTAGES = 3, /* Measurements of less-critical system voltages */
    SystemDataId_CURRENT_CONTROL_MONITOR = 4, /* Current control monitor data */
    SystemDataId_SYSTEM_OBSERVER_MONITOR = 5, /* System observer monitor data */
    SystemDataId_INNER_LOOP_VOLTAGES = 6, /* Voltage measurements from the inner loop controller */
    /* Individual Data Streams */
    SystemDataId_INDIVIDUAL_DATA_STREAMS_START = 100, /* Start of individual data streams. Used for iteration only. */
    SystemDataId_ADC_BUS_VOLTAGE = 101 /* DC bus voltage input to the motor controller */
} SystemDataId;

/* Bitfield values to determine the health of a chunk */
typedef enum _StreamDataMessage_Flags {
    StreamDataMessage_Flags_VALID = 1, /* Data is valid */
    StreamDataMessage_Flags_OUT_OF_SYNC = 2, /* Data was not logged at the requested rate */
    StreamDataMessage_Flags_DEGRADED = 4 /* Processing is still ok, but data is in a degraded state */
} StreamDataMessage_Flags;

/* Struct definitions */
/* Message type for announcing the current system tick */
typedef struct _SystemTickMessage {
    Header header;
    uint32_t tick; /* System time in milliseconds */
} SystemTickMessage;

typedef PB_BYTES_ARRAY_T(128) ConsoleMessage_data_t;
/* Message type for streaming out console messages in real time */
typedef struct _ConsoleMessage {
    Header header;
    uint8_t this_frame; /* Which frame is this? */
    uint8_t total_frames; /* How many frames are there? */
    ConsoleMessage_data_t data; /* Data payload */
} ConsoleMessage;

/* Message type for announcing some device descriptions */
typedef struct _SystemInfoMessage {
    Header header;
    uint32_t systemTick; /* System time in milliseconds */
    char swVersion[16]; /* Software version */
    char description[16]; /* Device description */
    char serialNumber[16]; /* Serial number */
} SystemInfoMessage;

/* Message type for announcing the current system status */
typedef struct _SystemStatusMessage {
    Header header;
    uint32_t systemTick; /* System time in milliseconds */
    MotorCtrlState motorCtrlState; /* High level current motor control state */
} SystemStatusMessage;

typedef struct _StreamRequestMessage {
    Header header;
    SystemDataId id; /* Data stream to act on */
    float rate; /* Periodic output rate in Hz */
    bool active; /* True to enable the stream, False for disable */
} StreamRequestMessage;

typedef PB_BYTES_ARRAY_T(4) StreamDataMessage_Chunk_payload_t;
/* Raw chunk of data representing a single stream */
typedef struct _StreamDataMessage_Chunk {
    SystemDataId id; /* Data stream ID */
    uint8_t flags; /* Status flags for the chunk */
    uint32_t timestamp; /* System time of the data payload in microseconds */
    StreamDataMessage_Chunk_payload_t payload; /* Data payload */
} StreamDataMessage_Chunk;

typedef struct _StreamDataMessage {
    Header header;
    pb_size_t chunks_count;
    StreamDataMessage_Chunk chunks[10];
} StreamDataMessage;

typedef PB_BYTES_ARRAY_T(80) SystemDataMessage_payload_t;
/* Message type for streaming out raw data from the system in real time */
typedef struct _SystemDataMessage {
    Header header;
    SystemDataId id; /* Which data stream is this? */
    uint32_t timestamp; /* System time of measurement in microseconds */
    bool has_payload;
    SystemDataMessage_payload_t payload; /* Data payload */
} SystemDataMessage;

/* Data payload type for SystemDataId::ADC_PHASE_CURRENTS */
typedef struct _ADCPhaseCurrentsPayload {
    float ia; /* Phase A current in Amps */
    float ib; /* Phase B current in Amps */
    float ic; /* Phase C current in Amps */
} ADCPhaseCurrentsPayload;

/* Data payload type for SystemDataId::PWM_COMMANDS */
typedef struct _ADCPhaseVoltagesPayload {
    float va; /* Phase A voltage command in Volts */
    float vb; /* Phase B voltage command in Volts */
    float vc; /* Phase C voltage command in Volts */
} ADCPhaseVoltagesPayload;

/* Data payload type for SystemDataId::ADC_SYSTEM_VOLTAGES */
typedef struct _ADCSystemVoltagesPayload {
    float v_mcu; /* Logic level supply voltage in Volts */
    float v_dc_link; /* DC link voltage in Volts */
    float v_temp; /* Temperature sensor voltage in Volts */
    float v_isense; /* Current sense amplifier voltage reference in Volts */
} ADCSystemVoltagesPayload;

typedef struct _CurrentControlMonitorPayload {
    float ia; /* Phase A current in Amps */
    float ib; /* Phase B current in Amps */
    float ic; /* Phase C current in Amps */
    float id_ref; /* D-axis current reference in Amps */
    float iq_ref; /* Q-axis current reference in Amps */
    float id; /* D-axis actual current in Amps */
    float iq; /* Q-axis actual current in Amps */
    float vd; /* D-axis voltage command in Volts */
    float vq; /* Q-axis voltage command in Volts */
    float va; /* Voltage command for the Alpha axis in Volts */
    float vb; /* Voltage command for the Beta axis in Volts */
} CurrentControlMonitorPayload;

typedef struct _SystemObserverMonitorPayload {
    float theta_est; /* Estimated electrical angle in radians */
    float omega_est; /* Estimated electrical speed in radians per second */
} SystemObserverMonitorPayload;

/* Message payload type for SystemDataId::INNER_LOOP_VOLTAGES */
typedef struct _InnerLoopVoltageMonitorPayload {
    float va; /* Measured phase A voltage */
    float vb; /* Measured phase B voltage */
    float vc; /* Measured phase C voltage */
    float alpha; /* Measured alpha axis voltage */
    float beta; /* Measured beta axis voltage */
} InnerLoopVoltageMonitorPayload;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _SystemDataId_MIN SystemDataId_SYS_DATA_INVALID
#define _SystemDataId_MAX SystemDataId_ADC_BUS_VOLTAGE
#define _SystemDataId_ARRAYSIZE ((SystemDataId)(SystemDataId_ADC_BUS_VOLTAGE+1))

#define _StreamDataMessage_Flags_MIN StreamDataMessage_Flags_VALID
#define _StreamDataMessage_Flags_MAX StreamDataMessage_Flags_DEGRADED
#define _StreamDataMessage_Flags_ARRAYSIZE ((StreamDataMessage_Flags)(StreamDataMessage_Flags_DEGRADED+1))




#define SystemStatusMessage_motorCtrlState_ENUMTYPE MotorCtrlState

#define StreamRequestMessage_id_ENUMTYPE SystemDataId


#define StreamDataMessage_Chunk_id_ENUMTYPE SystemDataId

#define SystemDataMessage_id_ENUMTYPE SystemDataId








/* Initializer values for message structs */
#define SystemTickMessage_init_default           {Header_init_default, 0}
#define ConsoleMessage_init_default              {Header_init_default, 0, 0, {0, {0}}}
#define SystemInfoMessage_init_default           {Header_init_default, 0, "", "", ""}
#define SystemStatusMessage_init_default         {Header_init_default, 0, _MotorCtrlState_MIN}
#define StreamRequestMessage_init_default        {Header_init_default, _SystemDataId_MIN, 0, 0}
#define StreamDataMessage_init_default           {Header_init_default, 0, {StreamDataMessage_Chunk_init_default, StreamDataMessage_Chunk_init_default, StreamDataMessage_Chunk_init_default, StreamDataMessage_Chunk_init_default, StreamDataMessage_Chunk_init_default, StreamDataMessage_Chunk_init_default, StreamDataMessage_Chunk_init_default, StreamDataMessage_Chunk_init_default, StreamDataMessage_Chunk_init_default, StreamDataMessage_Chunk_init_default}}
#define StreamDataMessage_Chunk_init_default     {_SystemDataId_MIN, 0, 0, {0, {0}}}
#define SystemDataMessage_init_default           {Header_init_default, _SystemDataId_MIN, 0, false, {0, {0}}}
#define ADCPhaseCurrentsPayload_init_default     {0, 0, 0}
#define ADCPhaseVoltagesPayload_init_default     {0, 0, 0}
#define ADCSystemVoltagesPayload_init_default    {0, 0, 0, 0}
#define CurrentControlMonitorPayload_init_default {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define SystemObserverMonitorPayload_init_default {0, 0}
#define InnerLoopVoltageMonitorPayload_init_default {0, 0, 0, 0, 0}
#define SystemTickMessage_init_zero              {Header_init_zero, 0}
#define ConsoleMessage_init_zero                 {Header_init_zero, 0, 0, {0, {0}}}
#define SystemInfoMessage_init_zero              {Header_init_zero, 0, "", "", ""}
#define SystemStatusMessage_init_zero            {Header_init_zero, 0, _MotorCtrlState_MIN}
#define StreamRequestMessage_init_zero           {Header_init_zero, _SystemDataId_MIN, 0, 0}
#define StreamDataMessage_init_zero              {Header_init_zero, 0, {StreamDataMessage_Chunk_init_zero, StreamDataMessage_Chunk_init_zero, StreamDataMessage_Chunk_init_zero, StreamDataMessage_Chunk_init_zero, StreamDataMessage_Chunk_init_zero, StreamDataMessage_Chunk_init_zero, StreamDataMessage_Chunk_init_zero, StreamDataMessage_Chunk_init_zero, StreamDataMessage_Chunk_init_zero, StreamDataMessage_Chunk_init_zero}}
#define StreamDataMessage_Chunk_init_zero        {_SystemDataId_MIN, 0, 0, {0, {0}}}
#define SystemDataMessage_init_zero              {Header_init_zero, _SystemDataId_MIN, 0, false, {0, {0}}}
#define ADCPhaseCurrentsPayload_init_zero        {0, 0, 0}
#define ADCPhaseVoltagesPayload_init_zero        {0, 0, 0}
#define ADCSystemVoltagesPayload_init_zero       {0, 0, 0, 0}
#define CurrentControlMonitorPayload_init_zero   {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define SystemObserverMonitorPayload_init_zero   {0, 0}
#define InnerLoopVoltageMonitorPayload_init_zero {0, 0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define SystemTickMessage_header_tag             1
#define SystemTickMessage_tick_tag               2
#define ConsoleMessage_header_tag                1
#define ConsoleMessage_this_frame_tag            2
#define ConsoleMessage_total_frames_tag          3
#define ConsoleMessage_data_tag                  4
#define SystemInfoMessage_header_tag             1
#define SystemInfoMessage_systemTick_tag         2
#define SystemInfoMessage_swVersion_tag          3
#define SystemInfoMessage_description_tag        4
#define SystemInfoMessage_serialNumber_tag       5
#define SystemStatusMessage_header_tag           1
#define SystemStatusMessage_systemTick_tag       2
#define SystemStatusMessage_motorCtrlState_tag   3
#define StreamRequestMessage_header_tag          1
#define StreamRequestMessage_id_tag              2
#define StreamRequestMessage_rate_tag            3
#define StreamRequestMessage_active_tag          4
#define StreamDataMessage_Chunk_id_tag           1
#define StreamDataMessage_Chunk_flags_tag        2
#define StreamDataMessage_Chunk_timestamp_tag    3
#define StreamDataMessage_Chunk_payload_tag      4
#define StreamDataMessage_header_tag             1
#define StreamDataMessage_chunks_tag             2
#define SystemDataMessage_header_tag             1
#define SystemDataMessage_id_tag                 2
#define SystemDataMessage_timestamp_tag          3
#define SystemDataMessage_payload_tag            4
#define ADCPhaseCurrentsPayload_ia_tag           1
#define ADCPhaseCurrentsPayload_ib_tag           2
#define ADCPhaseCurrentsPayload_ic_tag           3
#define ADCPhaseVoltagesPayload_va_tag           1
#define ADCPhaseVoltagesPayload_vb_tag           2
#define ADCPhaseVoltagesPayload_vc_tag           3
#define ADCSystemVoltagesPayload_v_mcu_tag       1
#define ADCSystemVoltagesPayload_v_dc_link_tag   2
#define ADCSystemVoltagesPayload_v_temp_tag      3
#define ADCSystemVoltagesPayload_v_isense_tag    4
#define CurrentControlMonitorPayload_ia_tag      1
#define CurrentControlMonitorPayload_ib_tag      2
#define CurrentControlMonitorPayload_ic_tag      3
#define CurrentControlMonitorPayload_id_ref_tag  4
#define CurrentControlMonitorPayload_iq_ref_tag  5
#define CurrentControlMonitorPayload_id_tag      6
#define CurrentControlMonitorPayload_iq_tag      7
#define CurrentControlMonitorPayload_vd_tag      8
#define CurrentControlMonitorPayload_vq_tag      9
#define CurrentControlMonitorPayload_va_tag      10
#define CurrentControlMonitorPayload_vb_tag      11
#define SystemObserverMonitorPayload_theta_est_tag 3
#define SystemObserverMonitorPayload_omega_est_tag 4
#define InnerLoopVoltageMonitorPayload_va_tag    1
#define InnerLoopVoltageMonitorPayload_vb_tag    2
#define InnerLoopVoltageMonitorPayload_vc_tag    3
#define InnerLoopVoltageMonitorPayload_alpha_tag 4
#define InnerLoopVoltageMonitorPayload_beta_tag  5

/* Struct field encoding specification for nanopb */
#define SystemTickMessage_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  header,            1) \
X(a, STATIC,   REQUIRED, UINT32,   tick,              2)
#define SystemTickMessage_CALLBACK NULL
#define SystemTickMessage_DEFAULT NULL
#define SystemTickMessage_header_MSGTYPE Header

#define ConsoleMessage_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  header,            1) \
X(a, STATIC,   REQUIRED, UINT32,   this_frame,        2) \
X(a, STATIC,   REQUIRED, UINT32,   total_frames,      3) \
X(a, STATIC,   REQUIRED, BYTES,    data,              4)
#define ConsoleMessage_CALLBACK NULL
#define ConsoleMessage_DEFAULT NULL
#define ConsoleMessage_header_MSGTYPE Header

#define SystemInfoMessage_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  header,            1) \
X(a, STATIC,   REQUIRED, UINT32,   systemTick,        2) \
X(a, STATIC,   REQUIRED, STRING,   swVersion,         3) \
X(a, STATIC,   REQUIRED, STRING,   description,       4) \
X(a, STATIC,   REQUIRED, STRING,   serialNumber,      5)
#define SystemInfoMessage_CALLBACK NULL
#define SystemInfoMessage_DEFAULT NULL
#define SystemInfoMessage_header_MSGTYPE Header

#define SystemStatusMessage_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  header,            1) \
X(a, STATIC,   REQUIRED, UINT32,   systemTick,        2) \
X(a, STATIC,   REQUIRED, UENUM,    motorCtrlState,    3)
#define SystemStatusMessage_CALLBACK NULL
#define SystemStatusMessage_DEFAULT NULL
#define SystemStatusMessage_header_MSGTYPE Header

#define StreamRequestMessage_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  header,            1) \
X(a, STATIC,   REQUIRED, UENUM,    id,                2) \
X(a, STATIC,   REQUIRED, FLOAT,    rate,              3) \
X(a, STATIC,   REQUIRED, BOOL,     active,            4)
#define StreamRequestMessage_CALLBACK NULL
#define StreamRequestMessage_DEFAULT NULL
#define StreamRequestMessage_header_MSGTYPE Header

#define StreamDataMessage_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  header,            1) \
X(a, STATIC,   REPEATED, MESSAGE,  chunks,            2)
#define StreamDataMessage_CALLBACK NULL
#define StreamDataMessage_DEFAULT NULL
#define StreamDataMessage_header_MSGTYPE Header
#define StreamDataMessage_chunks_MSGTYPE StreamDataMessage_Chunk

#define StreamDataMessage_Chunk_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UENUM,    id,                1) \
X(a, STATIC,   REQUIRED, UINT32,   flags,             2) \
X(a, STATIC,   REQUIRED, UINT32,   timestamp,         3) \
X(a, STATIC,   REQUIRED, BYTES,    payload,           4)
#define StreamDataMessage_Chunk_CALLBACK NULL
#define StreamDataMessage_Chunk_DEFAULT NULL

#define SystemDataMessage_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  header,            1) \
X(a, STATIC,   REQUIRED, UENUM,    id,                2) \
X(a, STATIC,   REQUIRED, UINT32,   timestamp,         3) \
X(a, STATIC,   OPTIONAL, BYTES,    payload,           4)
#define SystemDataMessage_CALLBACK NULL
#define SystemDataMessage_DEFAULT NULL
#define SystemDataMessage_header_MSGTYPE Header

#define ADCPhaseCurrentsPayload_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, FLOAT,    ia,                1) \
X(a, STATIC,   REQUIRED, FLOAT,    ib,                2) \
X(a, STATIC,   REQUIRED, FLOAT,    ic,                3)
#define ADCPhaseCurrentsPayload_CALLBACK NULL
#define ADCPhaseCurrentsPayload_DEFAULT NULL

#define ADCPhaseVoltagesPayload_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, FLOAT,    va,                1) \
X(a, STATIC,   REQUIRED, FLOAT,    vb,                2) \
X(a, STATIC,   REQUIRED, FLOAT,    vc,                3)
#define ADCPhaseVoltagesPayload_CALLBACK NULL
#define ADCPhaseVoltagesPayload_DEFAULT NULL

#define ADCSystemVoltagesPayload_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, FLOAT,    v_mcu,             1) \
X(a, STATIC,   REQUIRED, FLOAT,    v_dc_link,         2) \
X(a, STATIC,   REQUIRED, FLOAT,    v_temp,            3) \
X(a, STATIC,   REQUIRED, FLOAT,    v_isense,          4)
#define ADCSystemVoltagesPayload_CALLBACK NULL
#define ADCSystemVoltagesPayload_DEFAULT NULL

#define CurrentControlMonitorPayload_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, FLOAT,    ia,                1) \
X(a, STATIC,   REQUIRED, FLOAT,    ib,                2) \
X(a, STATIC,   REQUIRED, FLOAT,    ic,                3) \
X(a, STATIC,   REQUIRED, FLOAT,    id_ref,            4) \
X(a, STATIC,   REQUIRED, FLOAT,    iq_ref,            5) \
X(a, STATIC,   REQUIRED, FLOAT,    id,                6) \
X(a, STATIC,   REQUIRED, FLOAT,    iq,                7) \
X(a, STATIC,   REQUIRED, FLOAT,    vd,                8) \
X(a, STATIC,   REQUIRED, FLOAT,    vq,                9) \
X(a, STATIC,   REQUIRED, FLOAT,    va,               10) \
X(a, STATIC,   REQUIRED, FLOAT,    vb,               11)
#define CurrentControlMonitorPayload_CALLBACK NULL
#define CurrentControlMonitorPayload_DEFAULT NULL

#define SystemObserverMonitorPayload_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, FLOAT,    theta_est,         3) \
X(a, STATIC,   REQUIRED, FLOAT,    omega_est,         4)
#define SystemObserverMonitorPayload_CALLBACK NULL
#define SystemObserverMonitorPayload_DEFAULT NULL

#define InnerLoopVoltageMonitorPayload_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, FLOAT,    va,                1) \
X(a, STATIC,   REQUIRED, FLOAT,    vb,                2) \
X(a, STATIC,   REQUIRED, FLOAT,    vc,                3) \
X(a, STATIC,   REQUIRED, FLOAT,    alpha,             4) \
X(a, STATIC,   REQUIRED, FLOAT,    beta,              5)
#define InnerLoopVoltageMonitorPayload_CALLBACK NULL
#define InnerLoopVoltageMonitorPayload_DEFAULT NULL

extern const pb_msgdesc_t SystemTickMessage_msg;
extern const pb_msgdesc_t ConsoleMessage_msg;
extern const pb_msgdesc_t SystemInfoMessage_msg;
extern const pb_msgdesc_t SystemStatusMessage_msg;
extern const pb_msgdesc_t StreamRequestMessage_msg;
extern const pb_msgdesc_t StreamDataMessage_msg;
extern const pb_msgdesc_t StreamDataMessage_Chunk_msg;
extern const pb_msgdesc_t SystemDataMessage_msg;
extern const pb_msgdesc_t ADCPhaseCurrentsPayload_msg;
extern const pb_msgdesc_t ADCPhaseVoltagesPayload_msg;
extern const pb_msgdesc_t ADCSystemVoltagesPayload_msg;
extern const pb_msgdesc_t CurrentControlMonitorPayload_msg;
extern const pb_msgdesc_t SystemObserverMonitorPayload_msg;
extern const pb_msgdesc_t InnerLoopVoltageMonitorPayload_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define SystemTickMessage_fields &SystemTickMessage_msg
#define ConsoleMessage_fields &ConsoleMessage_msg
#define SystemInfoMessage_fields &SystemInfoMessage_msg
#define SystemStatusMessage_fields &SystemStatusMessage_msg
#define StreamRequestMessage_fields &StreamRequestMessage_msg
#define StreamDataMessage_fields &StreamDataMessage_msg
#define StreamDataMessage_Chunk_fields &StreamDataMessage_Chunk_msg
#define SystemDataMessage_fields &SystemDataMessage_msg
#define ADCPhaseCurrentsPayload_fields &ADCPhaseCurrentsPayload_msg
#define ADCPhaseVoltagesPayload_fields &ADCPhaseVoltagesPayload_msg
#define ADCSystemVoltagesPayload_fields &ADCSystemVoltagesPayload_msg
#define CurrentControlMonitorPayload_fields &CurrentControlMonitorPayload_msg
#define SystemObserverMonitorPayload_fields &SystemObserverMonitorPayload_msg
#define InnerLoopVoltageMonitorPayload_fields &InnerLoopVoltageMonitorPayload_msg

/* Maximum encoded size of messages (where known) */
#define ADCPhaseCurrentsPayload_size             15
#define ADCPhaseVoltagesPayload_size             15
#define ADCSystemVoltagesPayload_size            20
#define ConsoleMessage_size                      149
#define CurrentControlMonitorPayload_size        55
#define InnerLoopVoltageMonitorPayload_size      25
#define SYSTEM_DATA_PB_H_MAX_SIZE                StreamDataMessage_size
#define StreamDataMessage_Chunk_size             17
#define StreamDataMessage_size                   202
#define StreamRequestMessage_size                21
#define SystemDataMessage_size                   102
#define SystemInfoMessage_size                   69
#define SystemObserverMonitorPayload_size        10
#define SystemStatusMessage_size                 20
#define SystemTickMessage_size                   18

#ifdef __cplusplus
} /* extern "C" */
#endif

#ifdef __cplusplus
/* Message descriptors for nanopb */
namespace nanopb {
template <>
struct MessageDescriptor<SystemTickMessage> {
    static PB_INLINE_CONSTEXPR const pb_size_t fields_array_length = 2;
    static inline const pb_msgdesc_t* fields() {
        return &SystemTickMessage_msg;
    }
};
template <>
struct MessageDescriptor<ConsoleMessage> {
    static PB_INLINE_CONSTEXPR const pb_size_t fields_array_length = 4;
    static inline const pb_msgdesc_t* fields() {
        return &ConsoleMessage_msg;
    }
};
template <>
struct MessageDescriptor<SystemInfoMessage> {
    static PB_INLINE_CONSTEXPR const pb_size_t fields_array_length = 5;
    static inline const pb_msgdesc_t* fields() {
        return &SystemInfoMessage_msg;
    }
};
template <>
struct MessageDescriptor<SystemStatusMessage> {
    static PB_INLINE_CONSTEXPR const pb_size_t fields_array_length = 3;
    static inline const pb_msgdesc_t* fields() {
        return &SystemStatusMessage_msg;
    }
};
template <>
struct MessageDescriptor<StreamRequestMessage> {
    static PB_INLINE_CONSTEXPR const pb_size_t fields_array_length = 4;
    static inline const pb_msgdesc_t* fields() {
        return &StreamRequestMessage_msg;
    }
};
template <>
struct MessageDescriptor<StreamDataMessage> {
    static PB_INLINE_CONSTEXPR const pb_size_t fields_array_length = 2;
    static inline const pb_msgdesc_t* fields() {
        return &StreamDataMessage_msg;
    }
};
template <>
struct MessageDescriptor<StreamDataMessage_Chunk> {
    static PB_INLINE_CONSTEXPR const pb_size_t fields_array_length = 4;
    static inline const pb_msgdesc_t* fields() {
        return &StreamDataMessage_Chunk_msg;
    }
};
template <>
struct MessageDescriptor<SystemDataMessage> {
    static PB_INLINE_CONSTEXPR const pb_size_t fields_array_length = 4;
    static inline const pb_msgdesc_t* fields() {
        return &SystemDataMessage_msg;
    }
};
template <>
struct MessageDescriptor<ADCPhaseCurrentsPayload> {
    static PB_INLINE_CONSTEXPR const pb_size_t fields_array_length = 3;
    static inline const pb_msgdesc_t* fields() {
        return &ADCPhaseCurrentsPayload_msg;
    }
};
template <>
struct MessageDescriptor<ADCPhaseVoltagesPayload> {
    static PB_INLINE_CONSTEXPR const pb_size_t fields_array_length = 3;
    static inline const pb_msgdesc_t* fields() {
        return &ADCPhaseVoltagesPayload_msg;
    }
};
template <>
struct MessageDescriptor<ADCSystemVoltagesPayload> {
    static PB_INLINE_CONSTEXPR const pb_size_t fields_array_length = 4;
    static inline const pb_msgdesc_t* fields() {
        return &ADCSystemVoltagesPayload_msg;
    }
};
template <>
struct MessageDescriptor<CurrentControlMonitorPayload> {
    static PB_INLINE_CONSTEXPR const pb_size_t fields_array_length = 11;
    static inline const pb_msgdesc_t* fields() {
        return &CurrentControlMonitorPayload_msg;
    }
};
template <>
struct MessageDescriptor<SystemObserverMonitorPayload> {
    static PB_INLINE_CONSTEXPR const pb_size_t fields_array_length = 2;
    static inline const pb_msgdesc_t* fields() {
        return &SystemObserverMonitorPayload_msg;
    }
};
template <>
struct MessageDescriptor<InnerLoopVoltageMonitorPayload> {
    static PB_INLINE_CONSTEXPR const pb_size_t fields_array_length = 5;
    static inline const pb_msgdesc_t* fields() {
        return &InnerLoopVoltageMonitorPayload_msg;
    }
};
}  // namespace nanopb

#endif  /* __cplusplus */


#endif
