/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "system_data.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(SystemTickMessage, SystemTickMessage, AUTO)


PB_BIND(ConsoleMessage, ConsoleMessage, AUTO)


PB_BIND(SystemInfoMessage, SystemInfoMessage, AUTO)


PB_BIND(SystemStatusMessage, SystemStatusMessage, AUTO)


PB_BIND(StreamRequestMessage, StreamRequestMessage, AUTO)


PB_BIND(StreamDataMessage, StreamDataMessage, AUTO)


PB_BIND(StreamDataMessage_Chunk, StreamDataMessage_Chunk, AUTO)


PB_BIND(SystemDataMessage, SystemDataMessage, AUTO)


PB_BIND(ADCPhaseCurrentsPayload, ADCPhaseCurrentsPayload, AUTO)


PB_BIND(ADCPhaseVoltagesPayload, ADCPhaseVoltagesPayload, AUTO)


PB_BIND(ADCSystemVoltagesPayload, ADCSystemVoltagesPayload, AUTO)


PB_BIND(CurrentControlMonitorPayload, CurrentControlMonitorPayload, AUTO)


PB_BIND(SystemObserverMonitorPayload, SystemObserverMonitorPayload, AUTO)


PB_BIND(InnerLoopVoltageMonitorPayload, InnerLoopVoltageMonitorPayload, AUTO)









